### ISSUE TITLE
Update for 0.8.x?

### ISSUE THREAD

**Issue by PhluXx1** [bsas/scene-backup-tool#1]
Thanks for this great module it has saved me tonnes of headaches. Do you have any plans to update the module to version 0.8.6?

**Comment by bsas** [comment]
Glad it helped anyone besides me :D...

Yes! I tested and it is working fine with 0.8.x, but you have the annoying warning message, I know. I will fix it as soon as I can but I am not in my house until the 12th :(

**Comment by PhluXx1** [comment]
Thanks and keep up the great work! You've done an awesome job developing a very useful module and I'm sure it's helped loads of people.
