### ISSUE TITLE
Thanks for v9 Update

### ISSUE THREAD

**Issue by PhluXx1** [bsas/scene-backup-tool#2]
Thanks for the v9 update this is a must have module. Please be advised that the module is showing as being 0.7.9 ingame with the compatibility risk warning.

![image](https://user-images.githubusercontent.com/72770484/148530134-925e1fc8-2f84-47f0-931e-fa06963bfd03.png)

**Comment by bsas** [comment]
Just fixed on version 1.0.4.1, please try it out.
